const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#0A7C5C",
    background: "#F7F5F0",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#0A7C5C",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F5F0",
    secondaryForeground: "#0A7C5C",
    muted: "#F0EEEA",
    mutedForeground: "#6B7280",
    accent: "#F59E0B",
    accentForeground: "#1A1A2E",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E2DC",
    input: "#E5E2DC",
  },
  dark: {
    text: "#F5F3EE",
    tint: "#2ECC9A",
    background: "#0D1B2A",
    foreground: "#F5F3EE",
    card: "#162032",
    cardForeground: "#F5F3EE",
    primary: "#2ECC9A",
    primaryForeground: "#0D1B2A",
    secondary: "#1B3D30",
    secondaryForeground: "#2ECC9A",
    muted: "#162032",
    mutedForeground: "#9CA3AF",
    accent: "#FBBF24",
    accentForeground: "#0D1B2A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A2F",
    input: "#1E3A2F",
  },
  radius: 16,
};

export default colors;
