uploads = []
outputs = []

[[generated]]
id = "-NaN7YL9uRBD7Z9xDVLYL"
uri = "file://artifacts/shaale-vikas/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7qw4ZCoYv7S3TdU9wR4f5"
uri = "file://artifacts/shaale-vikas/assets/images/onboard1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "XcqjYUxeyQ0rXepLYSpHQ"
uri = "file://artifacts/shaale-vikas/assets/images/onboard2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "m9_6VDm-myEADtxfrf903"
uri = "file://artifacts/shaale-vikas/assets/images/onboard3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "x3YqvfIjn9NUiRgYCf_0V"
uri = "file://artifacts/shaale-vikas/assets/images/school_before.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jCgMLERKmOV4QwDYm6Sb0"
uri = "file://artifacts/shaale-vikas/assets/images/school_after.png"
type = "image"
title = "generated_image"
